select ename,sal from emp where mgr is null;
select ename,job,sal,comm from emp where comm is null || comm <= 0;
select empno,ename,job,comm from emp where comm is not null and comm > 0;
select ename,sal,mgr from emp where mgr is not null;
select ename from emp where ename like 'S%';
select ename from emp where ename like '%S';
select ename from emp where ename like '%E_';
select ename from emp where ename like '%N__';
select ename from emp where ename like '%A%';
select ename from emp where ename not like 'K%';
select * from emp where ename not like '%A%';
select count(*) from emp where job like '%CLERK%';
select max(sal) from emp where job = 'SALESMAN';
select min(HIREdate) '最早入职',max(HIREdate) '最晚入职' from emp;
select category_id,num from t_item where category_id = '163';
select category_id,title from t_item where category_id = '163';
select title,price from t_item where price < 100;
select title,price from t_item where title like '%联想%' and price > 40000;
select title,price from t_item where title like '%三木%' or price < 50;
select title,price from t_item where title  like '%三木%' or title like '%广博%' or title like '%齐心%';
select title,price from t_item where title not like '%联想%' and title not like '%戴尔%';
select title from t_item where title like '%联想%' and price > 10000;
select title from t_item where title like '%联想%' or title like '%戴尔%';
select title from t_item where title like '%联想%' or title like '%戴尔%' or title like '%三木%';
select title from t_item where title not like '%戴尔%';
select item_type,title,price from t_item where title like '%记事本%';
select item_type,title,price from t_item where item_type like '%力';
select title from t_item where title like '%联想%';
select title,sell_point from t_item where sell_point like '%赠%';
select empno,ename,job,sal from emp where sal between 1000 and 2000;
select ename,job,mgr,empno from emp where job = 'SALESMAN' and mgr is not null;
select empno,ename,job,sal from emp where ename like '%E%' and job not like 'MANAGER';

desc t_item;
desc emp;
select * from t_item;
select * from emp;